### ISSUE TITLE
Support reverse scroll

### ISSUE THREAD

**Issue by pferrel** [mongoid/mongoid-scroll#1]
Not sure how to contact you so I'll try here.

I have a bi-directional infinite scroll. I enter at an object defined by a query. It has some location in an infinite list defined by a sort order. Batches of objects are filled in downwards with skip/limit. If the order_by is simple and unique (like username), I reverse the sort and get objects above the entry point with skip/limit--since the order_by is reverse this gets object above.

When the order_by is complex, there is no way to define a query on the reverse sorted collection that gets to the same "entry point" as the forward order.

What I really want is to have negative skip values on the forward sorted collection. This would be ideal and this seems possible with a cursor but I haven't bothered learning about them since they are time limited.

For example, a sorted collection might have the following order_by:

```
scope :rating_watchable, order_by(avg_rating: :desc, release_date: :desc, title: :asc)
```

given that this has the unique "title" in it the list can be reversed. The "entry point" might be the first item with a rating of 3 defined like this

```
Object.rating_watchable.where(:avg_rating.gte => 3).skip(0).limit(BATCH_SIZE)
```

To scroll forward I simply increase the skip count. To scroll backward I have to reverse the sort order.  If I were using a simple sort order like alphabetical on a unique field this isn't a problem but for the one above it doesn't work. But in the example above I can't determine a "where" that puts me in exactly the same spot since the "where" will have to be relative. 

I think of the problem as a long list (defined by a sort order). I can find an entry point and save it's UUID. Then I'd like to move forward and back from that object in this list.

Will mongoid-scroll handle forward and reverse movement from some "entry point"?

**Comment by GCorbel** [comment]
11 years after, I did #38

**Comment by dblock** [comment]
Closing via https://github.com/mongoid/mongoid-scroll/pull/38!
