### ISSUE TITLE
Scroll without passing block does not return the expected items

### ISSUE THREAD

**Issue by asgerb** [mongoid/mongoid-scroll#17]
Hey there. First time trying my hand with `mongoid-scroll` so forgive me if my problem is due to confusion/lack of knowledge rather than an actual issue!

When using `scroll` without a block, I expected it to return the items starting from the passed cursor. Instead it just returns them from the very beginning.

If I pass it a block instead, it works as I would expect:

```ruby
cursor = nil

Item.desc(:field).limit(10).scroll(cursor) do |item, next_cursor|
  puts item.inspect # starts from the first item
  cursor = next_cursor
end

Item.desc(:field).limit(10).scroll(cursor) do |item, next_cursor|
  puts item.inspect # starts from the end of the last loop
end
```

But without passing it a block it always start from the beginning:

```ruby
cursor = nil

Item.desc(:field).limit(10).scroll(cursor) do |item, next_cursor|
  puts item.inspect # starts from the first item
  cursor = next_cursor
end

Item.desc(:field).limit(10).scroll(cursor).each do |item|
  puts item.inspect # starts from the first item again
end
```

Am I missing something?

**Comment by asgerb** [comment]
This seems to be caused by the `mongoid` integration only applying the selector to the criteria if a block is given. If no block is given it just returns the original criteria:
https://github.com/mongoid/mongoid-scroll/blob/master/lib/mongoid/criterion/scrollable.rb#L21-L29

The `mongo` integration on the other hand applies the selector to the returned criteria (which I would expect to be the correct implementation?): https://github.com/mongoid/mongoid-scroll/blob/master/lib/mongo/scrollable.rb#L15-L29

**Comment by dblock** [comment]
This looks like a clear bug. Care to PR a fix please?

**Comment by asgerb** [comment]
Hey @dblock, for sure I'll make a PR with the fix I've done 🙂

**Comment by dblock** [comment]
Fixed in https://github.com/mongoid/mongoid-scroll/pull/18.
