### ISSUE TITLE
Release v. Next

### ISSUE THREAD

**Issue by dblock** [mongoid/mongoid-scroll#21]
See https://github.com/mongoid/mongoid-scroll/blob/master/RELEASING.md (probably needs an update too since we increment versions after release).

**Comment by asgerb** [comment]
Hey @dblock, finally getting around to this, just wanted to check in which version this should be?

**Comment by asgerb** [comment]
So I just released my first gem it seems, sorry for it taking so long @dblock 😉

**Comment by dblock** [comment]
Amazing, thanks @asgerb. Care to try to add Mongoid 7 here?

**Comment by asgerb** [comment]
For sure!
