### ISSUE TITLE
Getting uninitialized constant

### ISSUE THREAD

**Issue by Altonymous** [mongoid/mongoid-scroll#24]
error_message: 
```
 - uninitialized constant Mongoid::Scroll::Cursor::Origin
    Origin::Selector.new
```
backtrace:
```
~/.gem/ruby/3.1.2/gems/mongoid-scroll-0.3.7/lib/mongoid/scroll/cursor.rb:20:in `criteria'
    ~/.gem/ruby/3.1.2/gems/mongoid-scroll-0.3.7/lib/mongoid/criteria/scrollable.rb:60:in `build_cursor_criteria'
    ~/.gem/ruby/3.1.2/gems/mongoid-scroll-0.3.7/lib/mongoid/criteria/scrollable.rb:10:in `scroll'
    ~/.gem/ruby/3.1.2/gems/slack-ruby-bot-server-1.2.1/lib/slack-ruby-bot-server/api/helpers/cursor_helpers.rb:19:in `paginate_by_cursor'
    ~/.gem/ruby/3.1.2/gems/slack-ruby-bot-server-1.2.1/lib/slack-ruby-bot-server/api/helpers/cursor_helpers.rb:47:in `paginate_and_sort_by_cursor'
    ~/.gem/ruby/3.1.2/gems/slack-ruby-bot-server-1.2.1/lib/slack-ruby-bot-server/api/endpoints/teams_endpoint.rb:29:in `block (2 levels) in \u003cclass:TeamsEndpoint\u003e'
```

This appears to be an error originating from another gem I'm using.  Perhaps something is misconfigured in my application, but I'm not sure where to begin.

**Comment by dblock** [comment]
What version of mongoid? I bet it's 8. It has been a while since we have updated this library. I would start by replacing Travis CI with GHA, and then adding mongoid 8 support.

**Comment by Altonymous** [comment]
> What version of mongoid? I bet it's 8. It has been a while since we have updated this library. I would start by replacing Travis CI with GHA, and then adding mongoid 8 support.

YEs it's version 8.

**Comment by dblock** [comment]
@Altonymous you know what to do, I can review/merge PRs

**Comment by dblock** [comment]
Added support for Mongoid 8 in #33 and CI in #34.
