### ISSUE TITLE
Add different ways to serialize cursors

### ISSUE THREAD

**Issue by FabienChaynes** [mongoid/mongoid-scroll#31]
Following a discussion in https://github.com/mongoid/mongoid-scroll/pull/28#issuecomment-1442498964, it might be interesting to add a way to serialize cursors to Base64.

Here are the points we already discussed in #28:

1. [Base64.strict_encode64](https://ruby-doc.org/stdlib-2.5.3/libdoc/base64/rdoc/Base64.html#method-i-strict_encode64) should be used to follow [RFC 4648](https://www.rfc-editor.org/rfc/rfc4648) and have an [URL-friendly](https://stackoverflow.com/a/49009467) string.
2. We should have a new cursor class (e.g. `Base64EncodedCursor`) inheriting from `Cursor` and overriding the `#to_s` method to return the Base64 serialization
3. We should keep in mind that later, it should be easy to add new ways to serialize cursors (e.g. `SignedBase64EncodedCursor`)
4. One of the issues of the subclassing would be that `Mongo::Scrollable`, `Mongoid::Criteria::Scrollable` and `Moped::Scrollable` are building new `Mongoid::Scroll::Cursor` to yield them. We'd have to find a way for them to build and return the other cursor classes when required.

A quick test was done in 73bb694. It's not usable, but we can use that as a source of inspiration.

**Comment by FabienChaynes** [comment]
About 4., you stated:

> I think the solution is to create scrollable modules, e.g. Mongoid::Scrollable::Base64Encoded that extends/includes/inherits Mongoid::Scrollable and supplies the cursor class.

The issue is that it doesn't provide a way for the gem user to specify which kind of cursor they want for a specific `*::Scrollable#scroll` call.
For example for a `Mongoid::Criteria::Scrollable`, it's actually included in `Mongoid::Criteria` and `#scroll` is called on a `Mongoid::Criteria`. I don't see how we could specify that the `Mongoid::Criteria` should include `Mongoid::Criteria::Scrollable::Base64Encoded` instead of `Mongoid::Criteria::Scrollable` for a given `#scroll` call.

Aside from the new option passed to the `#scroll` methods to define the cursor class I discussed about in https://github.com/mongoid/mongoid-scroll/pull/28#issuecomment-1440807583, I had a new idea:

In `Base64EncodedCursor` we could have a class method returning a `Base64EncodedCursor` from a `Cursor`. It'll look like this:
```ruby
def from_cursor(cursor)
  base64_encoded_cursor = new(nil, { field_type: cursor.field_type, field_name: cursor.field_name, direction: cursor.direction })
  base64_encoded_cursor.value = cursor.value
  base64_encoded_cursor.tiebreak_id = cursor.tiebreak_id
  base64_encoded_cursor
end
```
IMO codewise it's slightly better than the new option to `Scrollable#scroll`. But the developer experience is still not great, because once you have a cursor you'll need to use `Base64EncodedCursor.from_cursor(cursor).to_s`.

**Comment by dblock** [comment]
I think #32 and #33 close this!
